/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.market.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(OKCancelPage.class)
public class MarketUtilityPage extends javax.swing.JPanel {

    /**
     * Creates new form MarketUtilityPage
     */
    public MarketUtilityPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xIntegerField3 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField4 = new com.rameses.rcp.control.XIntegerField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xButton2 = new com.rameses.rcp.control.XButton();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        monthList1 = new com.rameses.enterprise.components.MonthList();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xButton1 = new com.rameses.rcp.control.XButton();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Entry");
        jPanel1.setBorder(xTitledBorder1);
        jPanel1.setLayout(new java.awt.CardLayout());

        xPanel1.setVisibleWhen("#{ prev != null }");

        xFormPanel3.setCaptionWidth(150);

        xLabel3.setExpression("Previous Entry");
        xLabel3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 18));
        xLabel3.setShowCaption(false);
        xFormPanel3.add(xLabel3);

        xLabel4.setCaption("Month / Year");
        xLabel4.setExpression("#{prev.month} #{prev.year}");
        xLabel4.setCaptionWidth(130);
        xLabel4.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel3.add(xLabel4);

        xLabel5.setCaption("Reading");
        xLabel5.setExpression("#{prev.reading}");
        xLabel5.setCaptionWidth(130);
        xLabel5.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel3.add(xLabel5);

        xLabel6.setExpression("New Entry");
        xLabel6.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 18));
        xLabel6.setShowCaption(false);
        xFormPanel3.add(xLabel6);

        xLabel7.setCaption("Month / Year");
        xLabel7.setExpression("#{entry.monthname} #{entry.year}");
        xLabel7.setCaptionWidth(130);
        xLabel7.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel3.add(xLabel7);

        xLabel8.setCaption("Capacity");
        xLabel8.setExpression("#{entry.capacity}");
        xLabel8.setCaptionWidth(130);
        xLabel8.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel3.add(xLabel8);

        xIntegerField3.setCaption("New Reading");
        xIntegerField3.setName("entry.reading"); // NOI18N
        xIntegerField3.setCaptionWidth(130);
        xIntegerField3.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xIntegerField3.setRequired(true);
        xFormPanel3.add(xIntegerField3);

        xIntegerField4.setCaption("Volume");
        xIntegerField4.setDepends(new String[] {"entry.reading"});
        xIntegerField4.setEditable(false);
        xIntegerField4.setName("entry.volume"); // NOI18N
        xIntegerField4.setCaptionWidth(130);
        xIntegerField4.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xIntegerField4.setRequired(true);
        xFormPanel3.add(xIntegerField4);

        xDecimalField2.setCaption("Amount");
        xDecimalField2.setName("entry.amount"); // NOI18N
        xDecimalField2.setCaptionWidth(130);
        xDecimalField2.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel3.add(xDecimalField2);

        xButton2.setCaption("");
        xButton2.setName("calcNextReadingDate"); // NOI18N
        xButton2.setImmediate(true);
        xButton2.setText("Calculate Amount");
        xButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(xButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(xPanel1, "card2");

        xPanel2.setVisibleWhen("#{ prev == null }");

        xFormPanel2.setCaptionWidth(150);

        monthList1.setCaption("Last Month");
        monthList1.setName("entry.month"); // NOI18N
        monthList1.setRequired(true);
        xFormPanel2.add(monthList1);

        xIntegerField1.setCaption("Year");
        xIntegerField1.setName("entry.year"); // NOI18N
        xIntegerField1.setRequired(true);
        xFormPanel2.add(xIntegerField1);

        xComboBox1.setCaption("Capacity");
        xComboBox1.setItems("capacityList");
        xComboBox1.setName("entry.capacity"); // NOI18N
        xComboBox1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xComboBox1.setRequired(true);
        xFormPanel2.add(xComboBox1);

        xIntegerField2.setCaption("Last Reading");
        xIntegerField2.setName("entry.reading"); // NOI18N
        xIntegerField2.setRequired(true);
        xFormPanel2.add(xIntegerField2);

        xDecimalField1.setCaption("Begin Balance");
        xDecimalField1.setName("entry.amount"); // NOI18N
        xDecimalField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xFormPanel2.add(xDecimalField1);

        xButton1.setCaption("");
        xButton1.setName("calcNextReadingDate"); // NOI18N
        xButton1.setImmediate(true);
        xButton1.setText("Get Next Reading Date");
        xButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout xPanel2Layout = new javax.swing.GroupLayout(xPanel2);
        xPanel2.setLayout(xPanel2Layout);
        xPanel2Layout.setHorizontalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addGroup(xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(xPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(xButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        xPanel2Layout.setVerticalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1.add(xPanel2, "card3");

        xFormPanel1.setCaptionWidth(150);

        xLabel1.setCaption("Account No");
        xLabel1.setExpression("#{entity.acctno}");
        xFormPanel1.add(xLabel1);

        xLabel2.setCaption("Account Name");
        xLabel2.setExpression("#{entity.acctname}");
        xFormPanel1.add(xLabel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xButton1ActionPerformed

    private void xButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.enterprise.components.MonthList monthList1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XIntegerField xIntegerField3;
    private com.rameses.rcp.control.XIntegerField xIntegerField4;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    // End of variables declaration//GEN-END:variables
}
