/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.market.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class MarketAccountCreatePage extends javax.swing.JPanel {

    /**
     * Creates new form MarketAccountCreatePage
     */
    public MarketAccountCreatePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        entityAddressLookup1 = new com.rameses.entity.components.EntityAddressLookup();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        jLabel1 = new javax.swing.JLabel();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        xList1 = new com.rameses.rcp.control.XList();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();

        setPreferredSize(new java.awt.Dimension(638, 541));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Account Information");
        jPanel1.setBorder(xTitledBorder1);

        xFormPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        xFormPanel1.setCaptionWidth(160);

        xLabel3.setCaption("Org");
        xLabel3.setExpression("#{entity.org.name}");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel3);

        xTextField2.setCaption("Acct No");
        xTextField2.setName("entity.acctno"); // NOI18N
        xTextField2.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xTextField2.setPreferredSize(new java.awt.Dimension(150, 20));
        xFormPanel1.add(xTextField2);

        xLabel1.setCaption("");
        xLabel1.setText("<html><i><b>Leave this blank for auto generated acctno</b></i></html>");
        xFormPanel1.add(xLabel1);

        xTextField1.setCaption("Acct Name");
        xTextField1.setName("entity.acctname"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField1);

        entityLookup1.setCaption("Owner");
        entityLookup1.setName("entity.owner"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 21));
        xFormPanel1.add(entityLookup1);

        entityAddressLookup1.setCaption("Owner Address");
        entityAddressLookup1.setDepends(new String[] {"entity.owner"});
        entityAddressLookup1.setName("entity.owner.address"); // NOI18N
        entityAddressLookup1.setParentIdName("entity.owner.objid");
        entityAddressLookup1.setPreferredSize(new java.awt.Dimension(0, 53));
        xFormPanel1.add(entityAddressLookup1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 63));

        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("entity.remarks"); // NOI18N
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel1.add(jScrollPane1);

        xComboBox2.setCaption("Payment Mode");
        xComboBox2.setItems("paymentModes");
        xComboBox2.setName("entity.paymentmode"); // NOI18N
        xComboBox2.setAllowNull(false);
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 27));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xPanel2.setCaption("Rate");
        xPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xPanel2.setOpaque(false);
        xPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 2));

        xDecimalField2.setCaption("Rate");
        xDecimalField2.setName("entity.rate"); // NOI18N
        xPanel2.add(xDecimalField2);

        jLabel1.setText("per");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 0, 4));
        xPanel2.add(jLabel1);

        xComboBox4.setCaption("Rate Type");
        xComboBox4.setDepends(new String[] {"entity.billtype"});
        xComboBox4.setItems("rateTypes");
        xComboBox4.setName("entity.ratetype"); // NOI18N
        xComboBox4.setVisibleWhen("#{ entity.paymentmode == 'MONTHLY' }");
        xComboBox4.setAllowNull(false);
        xComboBox4.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xComboBox4.setRequired(true);
        xPanel2.add(xComboBox4);

        xFormPanel1.add(xPanel2);

        xComboBox3.setCaption("Bill Group (Schedule)");
        xComboBox3.setDepends(new String[] {"entity.paymentmode"});
        xComboBox3.setItems("billGroups");
        xComboBox3.setName("entity.billgroupid"); // NOI18N
        xComboBox3.setAllowNull(false);
        xComboBox3.setDynamic(true);
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 27));
        xComboBox3.setRequired(true);
        xFormPanel1.add(xComboBox3);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 104));

        xList1.setCaption("Units");
        xList1.setExpression("#{ item.code } @ #{ item.rate } #{ item.ratetype }");
        xList1.setItems("entity.units");
        xList1.setName("selectedUnit"); // NOI18N
        xList1.setDynamic(true);
        xList1.setPreferredSize(new java.awt.Dimension(0, 100));
        jScrollPane2.setViewportView(xList1);

        xFormPanel1.add(jScrollPane2);

        xPanel1.setCaption("");
        xPanel1.setOpaque(false);
        xPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 2));

        xButton1.setName("addUnit"); // NOI18N
        xButton1.setImmediate(true);
        xButton1.setText("Add");
        xPanel1.add(xButton1);

        xButton2.setName("removeUnit"); // NOI18N
        xButton2.setImmediate(true);
        xButton2.setText("Remove");
        xPanel1.add(xButton2);

        xFormPanel1.add(xPanel1);

        xDecimalField1.setCaption("Area (sqm)");
        xDecimalField1.setName("entity.areasqm"); // NOI18N
        xFormPanel1.add(xDecimalField1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.entity.components.EntityAddressLookup entityAddressLookup1;
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XList xList1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
