/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.market.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author elmonazareno
 */
@Template(CrudFormPage.class)
public class MarketRentalUnitPage extends javax.swing.JPanel {

    /**
     * Creates new form MarketRentalUnitPage
     */
    public MarketRentalUnitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        jLabel1 = new javax.swing.JLabel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();

        xFormPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        xFormPanel1.setCaptionWidth(120);

        xLabel3.setCaption("Org");
        xLabel3.setExpression("#{entity.org.name}");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel3);

        xLabel1.setCaption("Current Account");
        xLabel1.setExpression("#{entity.account.acctno} - #{entity.account.acctname} ");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 18));
        xFormPanel1.add(xLabel1);

        xTextField1.setCaption("Code");
        xTextField1.setName("entity.code"); // NOI18N
        xTextField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xTextField1.setRequired(true);
        xTextField1.setSpaceChar('_');
        xFormPanel1.add(xTextField1);

        xIntegerField1.setCaption("Index No");
        xIntegerField1.setName("entity.indexno"); // NOI18N
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xDecimalField2.setCaption("Area (sqm)");
        xDecimalField2.setName("entity.areasqm"); // NOI18N
        xFormPanel1.add(xDecimalField2);

        xLookupField2.setCaption("Market Section");
        xLookupField2.setExpression("#{entity.section.name}");
        xLookupField2.setHandler("market_section:lookup");
        xLookupField2.setName("entity.section"); // NOI18N
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLookupField2);

        xPanel1.setCaption("Rate");
        xPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 2));

        xDecimalField1.setCaption("Rate");
        xDecimalField1.setName("entity.rate"); // NOI18N
        xPanel1.add(xDecimalField1);

        jLabel1.setText("per");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 0, 4));
        xPanel1.add(jLabel1);

        xComboBox2.setCaption("Rate Type");
        xComboBox2.setItems("rateTypes");
        xComboBox2.setName("entity.ratetype"); // NOI18N
        xComboBox2.setAllowNull(false);
        xComboBox2.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xComboBox2.setRequired(true);
        xPanel1.add(xComboBox2);

        xFormPanel1.add(xPanel1);

        xComboBox1.setCaption("Unit Type");
        xComboBox1.setItems("unitTypes");
        xComboBox1.setName("entity.unittype"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(120, 22));
        xFormPanel1.add(xComboBox1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
