/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.market.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class MarketAccountEditPage extends javax.swing.JPanel {

    /**
     * Creates new form MarketAccountEditPage
     */
    public MarketAccountEditPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frmContact = new com.rameses.rcp.control.XFormPanel();
        txtContact1 = new com.rameses.rcp.control.XTextField();
        txtContact2 = new com.rameses.rcp.control.XTextField();
        txtContact3 = new com.rameses.rcp.control.XTextField();
        frmApplicant = new com.rameses.rcp.control.XFormPanel();
        pnlApplicant = new com.rameses.rcp.control.XPanel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xButton2 = new com.rameses.rcp.control.XButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(768, 450));
        jPanel1.setLayout(new java.awt.CardLayout());

        frmContact.setVisibleWhen("#{ editContext == 'contact' }");
        frmContact.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        frmContact.setCaptionWidth(180);

        txtContact1.setCaption("Contact Name");
        txtContact1.setName("entity.contact.name"); // NOI18N
        txtContact1.setPreferredSize(new java.awt.Dimension(0, 20));
        txtContact1.setRequired(true);
        frmContact.add(txtContact1);

        txtContact2.setCaption("Contact Email");
        txtContact2.setName("entity.contact.email"); // NOI18N
        txtContact2.setPreferredSize(new java.awt.Dimension(0, 20));
        txtContact2.setRequired(true);
        txtContact2.setTextCase(com.rameses.rcp.constant.TextCase.NONE);
        frmContact.add(txtContact2);

        txtContact3.setCaption("Contact Mobile No");
        txtContact3.setName("entity.contact.mobileno"); // NOI18N
        txtContact3.setPreferredSize(new java.awt.Dimension(0, 20));
        txtContact3.setRequired(true);
        frmContact.add(txtContact3);

        jPanel1.add(frmContact, "card2");

        frmApplicant.setVisibleWhen("#{ editContext == 'applicant' }");
        frmApplicant.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        frmApplicant.setCaptionWidth(180);

        pnlApplicant.setCaption("Applicant");
        pnlApplicant.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        pnlApplicant.setPreferredSize(new java.awt.Dimension(0, 29));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0);
        flowLayout1.setAlignOnBaseline(true);
        pnlApplicant.setLayout(flowLayout1);

        xLabel5.setCaption("Applicant");
        xLabel5.setExpression("#{ entity.applicant.name }");
        xLabel5.setName("entity.applicant"); // NOI18N
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel5.setPreferredSize(new java.awt.Dimension(280, 25));
        pnlApplicant.add(xLabel5);

        xButton2.setName("lookupApplicant"); // NOI18N
        xButton2.setIconResource("images/buttons/search.png");
        xButton2.setImmediate(true);
        xButton2.setPreferredSize(new java.awt.Dimension(30, 29));
        xButton2.setTarget("");
        pnlApplicant.add(xButton2);

        frmApplicant.add(pnlApplicant);

        jPanel1.add(frmApplicant, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel frmApplicant;
    private com.rameses.rcp.control.XFormPanel frmContact;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XPanel pnlApplicant;
    private com.rameses.rcp.control.XTextField txtContact1;
    private com.rameses.rcp.control.XTextField txtContact2;
    private com.rameses.rcp.control.XTextField txtContact3;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XLabel xLabel5;
    // End of variables declaration//GEN-END:variables
}
