/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.market.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author Elmo Nazareno
 */
@Template(CrudFormPage.class)
public class MarketUtilityNewPage extends javax.swing.JPanel {

    /**
     * Creates new form MarketUtilityPage
     */
    public MarketUtilityNewPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        monthList1 = new com.rameses.enterprise.components.MonthList();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xButton1 = new com.rameses.rcp.control.XButton();

        xFormPanel2.setCaptionWidth(150);

        xLabel1.setCaption("Account No");
        xLabel1.setExpression("#{entity.account.acctno}");
        xFormPanel2.add(xLabel1);

        xLabel2.setCaption("Account Name");
        xLabel2.setExpression("#{entity.account.acctname}");
        xFormPanel2.add(xLabel2);

        xIntegerField1.setCaption("Year");
        xIntegerField1.setName("entity.year"); // NOI18N
        xIntegerField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xIntegerField1.setRequired(true);
        xFormPanel2.add(xIntegerField1);

        monthList1.setCaption("Month");
        monthList1.setName("entity.month"); // NOI18N
        monthList1.setRequired(true);
        xFormPanel2.add(monthList1);

        xIntegerField2.setCaption("Last Reading");
        xIntegerField2.setName("entity.reading"); // NOI18N
        xIntegerField2.setRequired(true);
        xFormPanel2.add(xIntegerField2);

        xDecimalField1.setCaption("Begin Balance");
        xDecimalField1.setName("entity.amount"); // NOI18N
        xDecimalField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xFormPanel2.add(xDecimalField1);

        xDateField1.setCaption("Next Bill Date");
        xDateField1.setName("entity.nextbilldate"); // NOI18N
        xDateField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xFormPanel2.add(xDateField1);

        xButton1.setCaption("");
        xButton1.setName("calcNextReadingDate"); // NOI18N
        xButton1.setImmediate(true);
        xButton1.setText("Get Next Reading Date");
        xButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButton1ActionPerformed(evt);
            }
        });
        xFormPanel2.add(xButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.enterprise.components.MonthList monthList1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    // End of variables declaration//GEN-END:variables
}
