/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.market.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;
import java.util.Date;

/**
 *
 * @author Elmo Nazareno
 */
@Template(OKCancelPage.class)
public class MarketChangeActionPage extends javax.swing.JPanel {

    /**
     * Creates new form MarketChangeActionPage
     */
    public MarketChangeActionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        entityAddressLookup1 = new com.rameses.entity.components.EntityAddressLookup();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xButton2 = new com.rameses.rcp.control.XButton();
        xComboBox6 = new com.rameses.rcp.control.XComboBox();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField3 = new com.rameses.rcp.control.XDecimalField();
        xDateField5 = new com.rameses.rcp.control.XDateField();

        jPanel1.setLayout(new java.awt.CardLayout());

        xPanel1.setName("owner"); // NOI18N

        xFormPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        xFormPanel1.setCaptionWidth(150);

        xTextField1.setCaption("Acct Name");
        xTextField1.setName("entity.acctname"); // NOI18N
        xTextField1.setVisibleWhen("#{ txntype == 'owner' }");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField1);

        entityLookup1.setCaption("Owner");
        entityLookup1.setName("entity.owner"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 21));
        entityLookup1.setVisibleWhen("#{ txntype == 'owner' }");
        xFormPanel1.add(entityLookup1);

        entityAddressLookup1.setCaption("Owner Address");
        entityAddressLookup1.setDepends(new String[] {"entity.owner"});
        entityAddressLookup1.setName("entity.owner.address"); // NOI18N
        entityAddressLookup1.setParentIdName("entity.owner.objid");
        entityAddressLookup1.setPreferredSize(new java.awt.Dimension(0, 53));
        entityAddressLookup1.setVisibleWhen("#{ txntype == 'owner' }");
        xFormPanel1.add(entityAddressLookup1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 63));

        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("entity.remarks"); // NOI18N
        xTextArea1.setVisibleWhen("#{ txntype == 'owner' }");
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel1.add(jScrollPane1);

        xDecimalField1.setCaption("New Rate");
        xDecimalField1.setName("entity.rate"); // NOI18N
        xDecimalField1.setVisibleWhen("#{ txntype == 'changerate' }");
        xDecimalField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xFormPanel1.add(xDecimalField1);

        xDateField1.setCaption("Effective Date");
        xDateField1.setName("entity.effectivedate"); // NOI18N
        xDateField1.setVisibleWhen("#{ txntype == 'changerate' }");
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xFormPanel1.add(xDateField1);

        xLookupField1.setCaption("Unit No");
        xLookupField1.setExpression("#{entity.unit.code}");
        xLookupField1.setHandler("market_rentalunit:open:lookup");
        xLookupField1.setName("entity.unit"); // NOI18N
        xLookupField1.setVisibleWhen("#{ txntype == 'rentalunit' }");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLookupField1);

        xLabel4.setCaption("Cluster");
        xLabel4.setDepends(new String[] {"entity.unit"});
        xLabel4.setExpression("#{entity.unit.cluster.market.name}  #{entity.unit.cluster.name} ");
        xLabel4.setVisibleWhen("#{ txntype == 'rentalunit' }");
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel4);

        xLabel6.setCaption("BIN");
        xLabel6.setExpression("#{entity.business.bin}");
        xLabel6.setVisibleWhen("#{ txntype == 'business' }");
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel1.add(xLabel6);

        xLabel2.setCaption("Trade Name");
        xLabel2.setExpression("#{entity.business.tradename}");
        xLabel2.setVisibleWhen("#{ txntype == 'business' }");
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Owner Name");
        xLabel3.setExpression("#{entity.business.owner.name}");
        xLabel3.setVisibleWhen("#{ txntype == 'business' }");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel1.add(xLabel3);

        xButton2.setCaption("");
        xButton2.setName("selectBusiness"); // NOI18N
        xButton2.setVisibleWhen("#{ txntype == 'business' }");
        xButton2.setImmediate(true);
        xButton2.setText("Select a business");
        xFormPanel1.add(xButton2);

        xComboBox6.setCaption("Mode of Payment");
        xComboBox6.setItems("lov.MARKET_PAYMENTMODE");
        xComboBox6.setName("entity.paymentmode"); // NOI18N
        xComboBox6.setVisibleWhen("#{ txntype == 'ledger' }");
        xComboBox6.setCaptionWidth(150);
        xComboBox6.setRequired(true);
        xFormPanel1.add(xComboBox6);

        xCheckBox1.setCaption("Rate Type");
        xCheckBox1.setCheckValue(1);
        xCheckBox1.setName("entity.fixedrate"); // NOI18N
        xCheckBox1.setUncheckValue(0);
        xCheckBox1.setVisibleWhen("#{ txntype == 'ledger' }");
        xCheckBox1.setText("Fixed Rate");
        xFormPanel1.add(xCheckBox1);

        xDateField2.setCaption("Start Date");
        xDateField2.setName("entity.startdate"); // NOI18N
        xDateField2.setVisibleWhen("#{ txntype == 'ledger' }");
        xDateField2.setRequired(true);
        xFormPanel1.add(xDateField2);

        xDecimalField2.setCaption("Extension Area (sqm)");
        xDecimalField2.setName("entity.extarea"); // NOI18N
        xDecimalField2.setVisibleWhen("#{ txntype == 'extarea' }");
        xFormPanel1.add(xDecimalField2);

        xDecimalField3.setCaption("Partial Balance");
        xDecimalField3.setName("entity.partialbalance"); // NOI18N
        xDecimalField3.setVisibleWhen("#{ txntype == 'lastdatepaid' }");
        xFormPanel1.add(xDecimalField3);

        xDateField5.setCaption("Paid Until Date");
        xDateField5.setName("entity.lastdatepaid"); // NOI18N
        xDateField5.setVisibleWhen("#{ txntype == 'lastdatepaid' }");
        xDateField5.setRequired(true);
        xFormPanel1.add(xDateField5);

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(xPanel1, "owner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.entity.components.EntityAddressLookup entityAddressLookup1;
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox6;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField5;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField3;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
