/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.market.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class MarketCashReceiptInitialPage extends javax.swing.JPanel {

    /**
     * Creates new form MarketCashReceiptInitialPage
     */
    public MarketCashReceiptInitialPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();

        xDataTable1.setHandler("typeListHandler");
        xDataTable1.setName("selectedType"); // NOI18N
        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "objid"}
                , new Object[]{"caption", " "}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"visible", true}
                , new Object[]{"visibleWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable1.setRequired(true);

        jLabel1.setText("Fill In the required entries and click next");

        jLabel2.setText("Select a transaction type");

        xRadio1.setCaption("Specify Owner");
        xRadio1.setName("searchOption"); // NOI18N
        xRadio1.setOptionValue("owner");
        xRadio1.setShowCaption(false);
        xRadio1.setText("Specify Owner");
        xFormPanel1.add(xRadio1);

        xLookupField1.setCaption("Name");
        xLookupField1.setDepends(new String[] {"searchOption"});
        xLookupField1.setExpression("#{ owner.name }");
        xLookupField1.setHandler("entity:lookup");
        xLookupField1.setName("owner"); // NOI18N
        xLookupField1.setVisibleWhen("#{ searchOption == 'owner' }");
        xLookupField1.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLookupField1);

        xRadio2.setCaption("Unit");
        xRadio2.setName("searchOption"); // NOI18N
        xRadio2.setOptionValue("unit");
        xRadio2.setShowCaption(false);
        xRadio2.setText("Specify Unit");
        xFormPanel1.add(xRadio2);

        xLookupField2.setCaption("Unit");
        xLookupField2.setDepends(new String[] {"searchOption"});
        xLookupField2.setExpression("#{ unit.code } #{ unit.currentaccount.owner.name }");
        xLookupField2.setHandler("market_rentalunit:active:lookup");
        xLookupField2.setName("unit"); // NOI18N
        xLookupField2.setText("#{ unit.code } - #{ unit.currentaccount.owner.name }");
        xLookupField2.setVisibleWhen("#{ searchOption == 'unit' }");
        xLookupField2.setCellPadding(new java.awt.Insets(0, 20, 0, 0));
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLookupField2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xDataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xDataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    // End of variables declaration//GEN-END:variables
}
